### ISSUE TITLE
function values_in_array BUG

### ISSUE THREAD

**Issue by xnzj** [spatie/array-functions#4]
function values_in_array($needles, array $haystack)
{
    if (!is_array($needles)) {
        $needles = [$needles];  // maybe $needles = (array)$needles
    }
    return count(array_intersect($needles, $haystack)) == count($needles);
}
PHP Parse error:  syntax error, unexpected '[' in /tmp/7b559a81-4950-4225-a2bd-a152befc3c10/code on line 4

**Comment by sebastiandedeyne** [comment]
What PHP version are you using? This looks like an error that would pop up using version 5.3 or lower, and the version requirement for this package is 5.6.0+.

If you're stuck on an old PHP version, I'd recommend you to just copy and paste an edited version of the function in your own code.

``` php
function values_in_array($needles, array $haystack)
{
    if (!is_array($needles)) {
        $needles = array($needles);
    }

    return count(array_intersect($needles, $haystack)) == count($needles);
}
```

**Comment by xnzj** [comment]
Yes, my PHP version is 5.3;
Thank you Thomas !
